services:
  db:
    build: database

  app :
    build: app

    volumes:
      - ./app:/home/rstudio/app
    environment:
      PASSWORD: password
    depends_on: 
      - db
    command: make -C '/home/rstudio/app' all

# To run use:
# docker compose up
